apiVersion: v1
kind: Secret
metadata:
  name: db-config
  namespace: integration
type: Opaque
stringData:
  db.properties: |
    db.sqlendpoint: <db-sqlendpoint>
    db.admin: <db-admin>
    db.password: <db-admin-password>